import { type Dictionary, t } from "intlayer";
import type { Metadata } from "next";

const metadataContent = {
	key: "page-metadata",
	content: {
		title: t({
			en: "Create Next App",
			ja: undefined
		}),
		description: t({
			en: "Generated by create next app",
			ja: undefined
		}),
	},
} satisfies Dictionary<Metadata>;

export default metadataContent;




